version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/dlopes7/go-appdynamics-rest-api
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v -coverprofile=coverage.txt -covermode=atomic ./appdrest/
      - run: bash <(curl -s https://codecov.io/bash)
